# Site settings
title: All Around Stone
email: bill@allaroundstone.ca
url: https://allaroundstone.ca
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2E7D32 #80B3FF
  secondary: 424242 #FD6E8A
  secondary-dark: 424242 #A2122F

# Footer settings
footer:
  copyright: All Around Stone
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/allaroundstone
  - title: facebook
    url: https://www.facebook.com/allaroundstoneCA

# Postal address (add as many lines as necessary)
address:
  - line: Greater Toronto Area

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
